### ISSUE TITLE
System.MethodAccessException when attempting to query CosmosDB using Table API

### ISSUE THREAD

**Issue by thered121** [Azure/azure-cosmos-table-dotnet#7] opened 2019-07-09 23:34 UTC
Attempting to use the Azure.Cosmos.Table libraries on an Ubuntu Linux container (specifically https://github.com/cloudfoundry/dotnet-core-buildpack/releases/tag/v2.2.12) is resulting in

System.MethodAccessException: Attempt by method 'Microsoft.Azure.Cosmos.Table.Extensions.TableExtensionExecutor.ExecuteQuerySegmented(Microsoft.Azure.Cosmos.Table.TableQuery1&lt;!!1&gt;, Microsoft.Azure.Cosmos.Table.TableContinuationToken, Microsoft.Azure.Cosmos.Table.CloudTableClient, Microsoft.Azure.Cosmos.Table.CloudTable, Microsoft.Azure.Cosmos.Table.EntityResolver1<!!0>, Microsoft.Azure.Cosmos.Table.TableRequestOptions, Microsoft.Azure.Cosmos.Table.OperationContext)' to access method 'Microsoft.Azure.Documents.Client.TaskHelper.InlineIfPossible<Microsoft.Azure.Cosmos.Table.TableQuerySegment1&lt;TResult&gt;&gt;(System.Func1<System.Threading.Tasks.Task1&lt;Microsoft.Azure.Cosmos.Table.TableQuerySegment1<!!0>>>, Microsoft.Azure.Documents.IRetryPolicy, System.Threading.CancellationToken)' failed.
I've tried both the 1.0.1 and the 1.0.2-preview versions of the library and get the same results.

The code base is proprietary so I can't share the whole project but I did attach the class file that makes the call to the API as well as a sanitized csproj file that lists the versions of .NET Core and the nuget packages I'm using.  

[code.zip](https://github.com/Azure/azure-cosmos-table-dotnet/files/3375108/code.zip)

**Comment by donghexu** [comment] 2019-07-10 23:22
@thered121 , what does your dependencies versions look like? Especially the Microsoft.Azure.Document.Core. Thanks

**Comment by wahyuen** [comment] 2019-08-08 05:42
getting an extremely similar exception attempting to port over to `Microsoft.Azure.Cosmos.Table`. This seems to only be a problem when initialising the `CloudStorageAccount` and subsequent `CloudTableClient` from a .Net Core WebAPI project. Unit tests and console applications performing the exact same calls seem to work completely ok.

```
Attempt by method 'Microsoft.Azure.Cosmos.Table.Logger.LogInformational(Microsoft.Azure.Cosmos.Table.OperationContext, System.String, System.Object[])' to access method 'Microsoft.Azure.Documents.DefaultTrace.TraceInformation(System.String)' failed.
```

Currently targetting `Microsoft.Azure.Cosmos` 3.1.0 and `Microsoft.Azure.DocumentDB.Core` 2.5.1 as we are still in the process of porting to the new SDK.

I've noticed in the latest preview, this has been even further restricted for `Microsoft.Azure.DocumentDB.Core` to 2.4.2, is this meant to be the long term solution? I would imagine this would place many customers such as us in a bind who are reliant on additional bug fixes and features in the latest versions of `Microsoft.Azure.DocumentDB.Core`

**Comment by donghexu** [comment] 2019-08-08 14:50
@wahyuen, thanks for the input. We recently also noticed this and has found there is an issue on DocumentDB.Core 2.5.1. We released new Table SDK to take it out. And we are working with the DocumentDB.Core team to fix their issue. Currently downgrade to any version lower than 2.5.1 should be good.

**Comment by vip32** [comment] 2019-08-15 08:48
experiencing a similar issue when using Microsoft.Azure.Cosmos.Table 1.0.1 and DocumentDB.Core 2.5.1.

System.MethodAccessException : Attempt by method 'Microsoft.Azure.Cosmos.Table.Logger.LogInformational(Microsoft.Azure.Cosmos.Table.OperationContext, System.String, System.Object[])' to access method 'Microsoft.Azure.Documents.DefaultTrace.TraceInformation(System.String)' failed.

downgrading to prior 2.5.1 is not an option for us :(

why is the newer 1.0.4 suddenly not allowed with 2.5.1? hotfix?
is see this package constraint  >= 2.1.3 && <= 2.4.2

for the older 1.0.1 package it is only >= 2.1.3  

confusing...

**Comment by bjthomson** [comment] 2020-01-02 17:30
There seems to be a regression bug. This was fixed, now reappeared:
`System.IO.FileLoadException
  HResult=0x80131040
  Message=Could not load file or assembly 'Microsoft.Azure.DocumentDB.Core, Version=2.4.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
  Source=Microsoft.Azure.Cosmos.Table
  StackTrace:
   at Microsoft.Azure.Cosmos.Table.CloudTableClient..ctor(StorageUri storageUri, StorageCredentials credentials, TableClientConfiguration configuration)
   at Microsoft.Azure.Cosmos.Table.CloudStorageAccountExtensions.CreateCloudTableClient(CloudStorageAccount account, TableClientConfiguration configuration)
   ...

Inner Exception 1:
FileLoadException: Could not load file or assembly 'Microsoft.Azure.DocumentDB.Core, Version=2.1.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
`
I knew I shouldnt have accepted all the updated nuget packages so soon in the new year.

**Comment by sakash279** [comment] 2020-02-10 22:27
@bjthomson - have you tried Microsoft.Azure.Cosmos.Table 1.0.6 with DocumentDB.Core version > 2.6 and above (thru 2.9.x)? I didn't run into issues while testing those versions. I believe there was a conflict due to some interface changes in specific versions of Microsoft.Azure.Cosmos.Table and DocumentDB.Core. 

If the above works, we can look into fixing the dependency issues in the next release.

**Comment by sakash279** [comment] 2020-09-08 06:47
no further reoccurence of the issue reported, so closing the issue as v1.0.7, 1.0.8 have not hit this.

**Closed as completed by sakash279** 2020-09-08 06:47 UTC
Labels: customer-reported
