### ISSUE TITLE
Nuget package dependency issue

### ISSUE THREAD

**Issue by rasmus-s** [Azure/azure-cosmos-table-dotnet#25] opened 2020-01-14 14:15 UTC
Can not have nuget package `Microsoft.Azure.Cosmos.Table` and `Microsoft.Azure.Search.Service` in same project due the `Microsoft.Azure.Cosmos.Table` had a hard dependency to the Odata = 7.5. Where `Microsoft.Azure.Search.Service` just want the Microsoft.Spatial greater then.

```
NU1107: Version conflict detected for Microsoft.Spatial. Install/reference Microsoft.Spatial 7.5.3 directly to project MyProjects.AzureSearch to resolve this issue. 
 MyProjects.AzureSearch -> Microsoft.Azure.Search 10.1.0 -> Microsoft.Azure.Search.Service 10.1.0 -> Microsoft.Spatial (>= 7.5.3) 
 MyProjects.AzureSearch -> MyProjects.Core -> Microsoft.Azure.Cosmos.Table 1.0.6 -> Microsoft.OData.Core 7.5.0 -> Microsoft.Spatial (= 7.5.0).
Package restore failed. Rolling back package changes for 'MyProjects.AzureSearch'.
```

Please make a more lose dependency to Odata / Spatial, so you can use multiple of azures features in same project.

**Comment by petro2050** [comment] 2020-04-06 15:08
I have the same issue. No update since January? I'm currently unable to install `Microsoft.Azure.Cosmos.Table`.

**Comment by PaulCheng** [comment] 2020-04-17 10:35
The issue was due to the hard-ver dependency on Spatial from OData.Core. The solution is to update OData.Core to a newer version greater than what Search.Service requires.
1. install table nuget pkg (current version 1.0.7), which references odata core 7.5.0
2. install newer version odata.core nuget pkg, for example 7.6.4
3. install search.service nuget pkg (current version 10.1.0)

**Comment by rnagpal** [comment] 2020-07-22 18:26
@rasmus-s @petro2050 : Could you confirm if this workaround helped?

**Comment by rasmus-s** [comment] 2020-07-27 07:12
@rnagpal  its still not working with the available nuget packages. 
![image](https://user-images.githubusercontent.com/8188529/88513801-44fd4500-cfe9-11ea-94f8-0f5b8c264e49.png)

Why not fix it in the nuget package (new release of the Search.service nuget) - instead of having developers to deal with a workaround.

**Comment by PaulCheng** [comment] 2020-07-28 05:12
@rasmus-s You can create a Support Request from Azure Portal, and we can assist you from there where we can set up a call if necessary.
To create new support request, from portal top right corner, click on ? then Help + support then Create a support request.

**Comment by sakash279** [comment] 2020-09-08 06:44
@rasmus-s, @petro2050  I can confirm that this issue is not present when using Tables v1.0.8 and Search 10.1.0, and should be fixed with updating OData.Core reference in the latest tables release. 
Please re-open if you're still hitting this issue, or file a ticket via portal.

**Closed as completed by sakash279** 2020-09-08 06:44 UTC
Labels: v1.0.9, customer-reported

**Comment by rasmus-s** [comment] 2020-09-09 13:15
Just testes at it worked fine with the latest NuGet versions.
